### ISSUE TITLE
coze 全屏以后，对话框很窄

### ISSUE THREAD

**Issue by wmf-maho** [xx025/strawberry#7]
![image](https://github.com/xx025/strawberry/assets/165783890/fcf4c66f-9433-4c4a-9c6b-b46644fdfd4b)
对话框只有中间的部分，跟之前的宽度不太一样，之前可以占到屏幕的三分之二左右的宽度，现在只有三分之一左右

**Comment by xx025** [comment]
已解决这个问题，

对话窗口遵循以下规则：
```css
      .chat_box_expand {
        min-width: 70vw;
        width: 1000px;
        max-width: 100%;
      }
```
